### ISSUE TITLE
Interactive IDE browser app for science.js

### ISSUE THREAD

**Issue by dnprock** [jasondavies/science.js#13]
It'd be easier to experiment with science.js if there's a shell or IDE. Python has IPython and R has R Studio. Maybe, an app written in mean.io.

**Comment by joearasin** [comment]
@dnprock Haven't given the options a go yet, but there have been a bunch of recent developments on this front. IPython turned into Jupyter, and has basically enabled support for non-python languages. Check out https://www.npmjs.com/package/ijavascript for instance.

Also, Tonic was launched recently and seems pretty cool, but I haven't given it a spin yet: https://tonicdev.com

**Comment by dnprock** [comment]
@joearasin thanks for the update. I plug science.js into tonicdev. Works quite well.

https://tonicdev.com/dnprock/55d606a236da250d00b847ce
