### ISSUE TITLE
Choice of license?

### ISSUE THREAD

**Issue by OAGr** [jasondavies/science.js#32]
Hi,

I noticed that the license page says it is copywritted. The license reads:
```
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
```

Does this mean that in all other packages that use this, they need to include that writing in their license? 

There are, as listed on Gitbub, 50 other packages here that use it, and some quick skimming does not list this in the few I've looked at. 

Maybe you would be willing to change to MIT or something standard?

**Comment by jasondavies** [comment]
This is the [3-Clause BSD license](https://opensource.org/licenses/BSD-3-Clause).  It's pretty standard. :)

**Comment by jasondavies** [comment]
> Does this mean that in all other packages that use this, they need to include that writing in their license?

No, it means that any *redistributions of this source code* need to retain the license.  The [MIT license](https://opensource.org/licenses/MIT) is the same:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

It's legalese to ensure that people don't publish open-source code without including that code's original license (or if they publish binaries, they need to include the license information in their documentation).

**Comment by OAGr** [comment]
Got it, I wasn't familiar with the 3-Clause license. Thanks for the response, and apologies for not understanding!
